#2149 Code review and improved user messages (#2252)

diff --git a/.travis.yml b/.travis.yml
--- a/.travis.yml
+++ b/.travis.yml
@@ -14,7 +14,7 @@ env:
 notifications:
   slack:
     rooms:
-      # token generated using travis encrypt "..." --add notifications.slack -r keptn/keptn --org
+      # generate token using travis encrypt "..." --add notifications.slack -r keptn/keptn --org
       - secure: NjL/yh3BkTig19hV7nH0q+XxNOxCGTuhdn69WV8tsR0TXp8gqQxD8pnyPX7/nNdkc9PPAUCLGdFlU+vsa3SFt1cdZCgi44lvqHPHBZCa1Sh2+CxqCPRe9NQzU8JJBwDO9OEezbL7Pbfoi7m56MVU6JfkX5RPwN7RLcyCUane/STu3NDBeJLvn0qhjXMFlfKibdwdWom+TZxMiWaZ3oX1omtE88fiHaEGDjTobO3GNR6er9Rd0peAf7LXyHPrJDC0Ss8bz6OVNPQQFtFVwHG/0zVGwZPDbDUw2U+C8DsBVofhPRKhK2g2o0VAESKgrREdDPyVtAsbOnxGnudyPv94whhNjv3aVLeNilNiujXBgeC5R8aWNc2FthDUdB1clKDRFpwiXi0F1J+3bYN498p7QI+Yrr9XSJA62ZCeUjm3Sg2zFs7VtILgCTSbPKzAL4XjSnzefAS8MnG137TnYbwyi9Z/5+XgmLwSguLRMnMlktOH4JxUvD4ImVO7OI/QYYLtUjqqSyjywEa4v+MsyuuqaiT2m4GFpIRKxB4C3c/kONn2kUAd9LM1eIcHonPNmvH36k41nTf+XLOOICy2i1+m1aB18q5yj8qeaQZenpf2WheflM9zDgZc3cku6ZnyZCMdlhLnKfMiCgf8sYvL8qnq1XY2yikeZt4SuMCKLl5wdlI=
     if: (branch = master or branch =~ ^release.*$) AND (type = cron OR type = push)
     on_success: never
@@ -29,14 +29,14 @@ before_install:
   fi
   export OS_TYPE
 
-# Build variables
+# build variables
 - export TZ=Europe/Vienna
 - VERSION="unknownversion"
 - DATE="$(date +'%Y%m%d.%H%M')"
 - GIT_SHA="$(git rev-parse --short HEAD)"
 - KUBE_CONSTRAINTS=">= 1.14, <= 1.18" # don't forget to udpate the defaults in cli/main.go
 
-# store all changed files from this commit in files.txt (careful - travis commit range might fail)
+# store all changed files from this commit in files.txt (note: Travis commit range might fail)
 - git diff --name-only $TRAVIS_COMMIT_RANGE > files.txt || echo ""
 # for non pull requests, use another type of commit range in addition
 - |
@@ -48,7 +48,7 @@ before_install:
 - cat files.txt
 - CHANGED_FILES=$(tr '\n' , < files.txt)
 
-# get current git branch name
+# get current Git branch name
 - GIT_BRANCH_NAME=$(git branch | grep \* | cut -d ' ' -f2)
 - BRANCH=$(if [ "$TRAVIS_PULL_REQUEST" == "false" ]; then echo $TRAVIS_BRANCH; else echo $TRAVIS_PULL_REQUEST_BRANCH; fi)
 - echo "TRAVIS_BRANCH=$TRAVIS_BRANCH, BRANCH=$BRANCH"
@@ -86,17 +86,15 @@ before_install:
 - INSTALLER_FOLDER="installer/"
 - export KEPTN_INSTALLER_VERSION=latest
 - export KEPTN_CLI_VERSION=latest
-- | # set installer image and cli version for release-branches
+- | # set installer version and CLI version for release branches
   if [[ $BRANCH =~ ^release.* ]]; then
     export KEPTN_INSTALLER_VERSION=${BRANCH#"release-"}
     export KEPTN_CLI_VERSION=${BRANCH#"release-"}
   fi
 # generate a lower-case slug of the branch name
 - BRANCH_SLUG=$(echo ${BRANCH} | sed -r s/[^a-zA-Z0-9]+/-/g | sed -r s/^-+\|-+$//g | tr A-Z a-z)
-### ATTENTION: please make sure installer is always the last in this list
 
-
-# template for gke tests
+# template for GKE tests
 gke_full: &gke_full
   os: linux
   before_script:
@@ -107,13 +105,13 @@ gke_full: &gke_full
     - echo ${GCLOUD_SERVICE_KEY} | base64 --decode > ~/gcloud-service-key.json
     - gcloud auth activate-service-account --key-file ~/gcloud-service-key.json
     - test/utils/download_and_install_keptn_cli.sh
-    # create gke cluster on gcloud
+    # create GKE cluster on gcloud
     - test/utils/gke_create_cluster.sh
   script:
     # test installation on gcloud
     - test/test_install_gke.sh
     - test/utils/check_bridge_availability.sh
-    # test onboarding and new-artifact for sockshop
+    # test onboarding and new-artifact for project sockshop
     - export PROJECT=sockshop
     - test/test_onboard_service.sh
     - test/test_new_artifact.sh
@@ -123,11 +121,11 @@ gke_full: &gke_full
     - test/test_delivery_assistant.sh
     - test/test_keptn_uninstall.sh
   after_success:
-    # delete google kubernetes cluster only on success (in case of an error we want to be able to dig into the cluster)
+    # delete Google Kubernetes cluster only on success (keep cluster in case of an error to dig into the cluster)
     - echo "Tests were successful, cleaning up the cluster now..."
     - test/utils/gke_delete_cluster.sh
   after_failure:
-    # print some debug info
+    # print debug info
     - echo "Keptn Installation Log:"
     - cat ~/.keptn/keptn-installer.log
     - kubectl get events --sort-by='.lastTimestamp' --all-namespaces
@@ -135,7 +133,7 @@ gke_full: &gke_full
     - kubectl get services --all-namespaces
     - kubectl get ingress --all-namespaces
 
-# template for gke tests
+# template for GKE tests
 gke_full_part1: &gke_full_part1
   os: linux
   before_script:
@@ -146,24 +144,24 @@ gke_full_part1: &gke_full_part1
     - echo ${GCLOUD_SERVICE_KEY} | base64 --decode > ~/gcloud-service-key.json
     - gcloud auth activate-service-account --key-file ~/gcloud-service-key.json
     - test/utils/download_and_install_keptn_cli.sh
-    # create gke cluster on gcloud
+    # create GKE cluster on gcloud
     - test/utils/gke_create_cluster.sh
     - test/utils/gke_authenticate_at_cluster.sh
   script:
     # test installation on gcloud
     - test/test_install_gke.sh
     - test/utils/check_bridge_availability.sh
-    # test onboarding and new-artifact for sockshop
+    # test onboarding and new-artifact for project sockshop
     - export PROJECT=sockshop
     - test/test_onboard_service.sh
     - test/test_new_artifact.sh
     - test/test_delete_project.sh
     - test/test_self_healing.sh
   after_success:
-    # delete google kubernetes cluster only on success (in case of an error we want to be able to dig into the cluster)
+    # delete Google Kubernetes cluster only on success (keep cluster in case of an error to dig into the cluster)
     - echo "Tests were successful, cleaning up the cluster now..."
   after_failure:
-    # print some debug info
+    # print debug info
     - echo "Keptn Installation Log:"
     - cat ~/.keptn/keptn-installer.log
     - kubectl get events --sort-by='.lastTimestamp' --all-namespaces
@@ -171,7 +169,7 @@ gke_full_part1: &gke_full_part1
     - kubectl get services --all-namespaces
     - kubectl get ingress --all-namespaces
 
-# template for gke tests
+# template for GKE tests
 gke_full_part2: &gke_full_part2
   os: linux
   before_script:
@@ -182,7 +180,7 @@ gke_full_part2: &gke_full_part2
     - echo ${GCLOUD_SERVICE_KEY} | base64 --decode > ~/gcloud-service-key.json
     - gcloud auth activate-service-account --key-file ~/gcloud-service-key.json
     - test/utils/download_and_install_keptn_cli.sh
-    # authenticate at gke cluster
+    # authenticate at GKE cluster
     - test/utils/gke_authenticate_at_cluster.sh
     - test/utils/gke_authenticate_at_keptn.sh
   script:
@@ -191,11 +189,11 @@ gke_full_part2: &gke_full_part2
     - test/test_delivery_assistant.sh
     - test/test_keptn_uninstall.sh
   after_success:
-    # delete google kubernetes cluster only on success (in case of an error we want to be able to dig into the cluster)
+    # delete Google Kubernetes cluster only on success (keep cluster in case of an error to dig into the cluster)
     - echo "Tests were successful, cleaning up the cluster now..."
     - test/utils/gke_delete_cluster.sh
   after_failure:
-    # print some debug info
+    # print debug info
     - echo "Keptn Installation Log:"
     - cat ~/.keptn/keptn-installer.log
     - kubectl get events --sort-by='.lastTimestamp' --all-namespaces
@@ -208,7 +206,7 @@ jobs:
   ##################################################################################
   # Jobs that are always executed
   ##################################################################################
-  - stage: Unit tests # Bridge
+  - stage: Unit tests # node for Keptn Bridge
     os: linux
     addons:
       chrome: stable
@@ -229,7 +227,7 @@ jobs:
   - stage: Unit tests # golang
     os: linux
     script:
-      - set -e # Fail the whole script whenever any command fails
+      - set -e # fail the whole script whenever any command fails
       - |
         cd "${CLI_FOLDER}"
         go test -race -coverprofile=coverage.txt -covermode=atomic -v ./...
@@ -392,7 +390,7 @@ jobs:
     services:
       - docker
     script:
-    - set -e # Fail the whole script whenever any command fails
+    - set -e # fail the whole script whenever any command fails
     - echo "$REGISTRY_PASSWORD" | docker login --username $REGISTRY_USER --password-stdin
     - ./writeManifest.sh
     - TYPE="$(echo $TRAVIS_BRANCH | cut -d'/' -f1)"
@@ -469,8 +467,7 @@ jobs:
       - echo ${GCLOUD_SERVICE_KEY} | base64 --decode > ~/gcloud-service-key.json
       - gcloud auth activate-service-account --key-file ~/gcloud-service-key.json
     script:
-      # overwrite version for release branches based on the branch name
-      - export VERSION=${BRANCH#"release-"}
+      - export VERSION=${BRANCH#"release-"} # overwrite version for release branches based on the branch name
       - echo "Build keptn cli"
       - cd ./cli
       - go test ./...
@@ -487,8 +484,7 @@ jobs:
       - gcloud auth activate-service-account --key-file ~/gcloud-service-key.json
       - source ./travis-scripts/install_helm.sh
     script:
-      # overwrite version for release branches based on the branch name
-      - export VERSION=${BRANCH#"release-"}
+      - export VERSION=${BRANCH#"release-"} # overwrite version for release branches based on the branch name
       - echo "Build installer"
       - source ./travis-scripts/build_release_installer.sh "${VERSION}"
 
@@ -498,10 +494,9 @@ jobs:
     services:
       - docker
     script:
-    - set -e # Fail the whole script whenever any command fails
+    - set -e # fail the whole script whenever any command fails
     - echo "$REGISTRY_PASSWORD" | docker login --username $REGISTRY_USER --password-stdin
-    # overwrite version for release branches based on the branch name
-    - export VERSION=${BRANCH#"release-"}
+    - export VERSION=${BRANCH#"release-"} # overwrite version for release branches based on the branch name
     - ./writeManifest.sh
     - source ./travis-scripts/build_release.sh "${API_IMAGE}" "${API_FOLDER}" "${GIT_SHA}" "${DATE}" "${VERSION}"
     - source ./travis-scripts/build_release.sh "${OS_ROUTE_SVC_IMAGE}" "${OS_ROUTE_SVC_FOLDER}" "${GIT_SHA}" "${DATE}" "${VERSION}"
@@ -522,10 +517,9 @@ jobs:
     services:
       - docker
     script:
-      - set -e # Fail the whole script whenever any command fails
+      - set -e # fail the whole script whenever any command fails
       - echo "$REGISTRY_PASSWORD" | docker login --username $REGISTRY_USER --password-stdin
-      # overwrite version for release branches based on the branch name
-      - export VERSION=${BRANCH#"release-"}
+      - export VERSION=${BRANCH#"release-"} # overwrite version for release branches based on the branch name
       - ./writeManifest.sh
       - source ./travis-scripts/build_release.sh "${SHIPYARD_SVC_IMAGE}" "${SHIPYARD_SVC_FOLDER}" "${GIT_SHA}" "${DATE}" "${VERSION}"
       - source ./travis-scripts/build_release.sh "${CONFIGURATION_SVC_IMAGE}" "${CONFIGURATION_SVC_FOLDER}" "${GIT_SHA}" "${DATE}" "${VERSION}"
@@ -541,28 +535,28 @@ jobs:
     if: branch = master AND type = cron # run for cron
     env:
       - GKE_VERSION=1.15
-    <<: *gke_full_part1 # use template
+    <<: *gke_full_part1 # use GKE template
 
   - stage: Test GKE Full with Istio - Pt. 1 (--platform=gke --use-case=continuous-delivery)
     if: branch = master AND type = cron # run for cron
     env:
       - GKE_VERSION=1.16
-    <<: *gke_full_part1 # use template
+    <<: *gke_full_part1 # use GKE template
 
   - stage: Test GKE Full with Istio - Pt. 2 (--platform=gke --use-case=continuous-delivery)
     if: branch = master AND type = cron # run for cron
     env:
       - GKE_VERSION=1.15
-    <<: *gke_full_part2 # use template
+    <<: *gke_full_part2 # use GKE template
 
   - stage: Test GKE Full with Istio - Pt. 2 (--platform=gke --use-case=continuous-delivery)
     if: branch = master AND type = cron # run for cron
     env:
       - GKE_VERSION=1.16
-    <<: *gke_full_part2 # use template
+    <<: *gke_full_part2 # use GKE template
 
   - stage: Test Minishift Standalone (--platform=openshift)
-    if: (branch = master or branch =~ ^release.*$) AND (type = cron OR type = push) # run for any change on master/release-* on push as well as cron
+    if: (branch = master or branch =~ ^release.*$) AND (type = cron OR type = push) # run for any change on master/release-* on push and cron
     os: linux
     before_script:
       # download and install kubectl
@@ -571,8 +565,9 @@ jobs:
       - test/utils/download_and_install_oc_cli.sh
       - test/utils/minishift_create_cluster.sh
     script:
-      - kubectl get nodes || travis_terminate 1 # sanity check that the K8s cluster is available
-      # finally install keptn quality gates
+      # sanity check that the K8s cluster is available
+      - kubectl get nodes || travis_terminate 1      
+      # install keptn quality gates
       - test/test_install_minishift_quality_gates.sh
       - keptn status
       - export PROJECT=musicshop
@@ -580,10 +575,10 @@ jobs:
       - export DYNATRACE_SLI_SERVICE_VERSION=master
       - test/test_quality_gates_standalone.sh
     after_success:
-      # delete kubernetes cluster only on success (in case of an error we want to be able to dig into the cluster)
+      # delete Google Kubernetes cluster only on success (keep cluster in case of an error to dig into the cluster)
       - echo "Tests were successful, cleaning up the cluster now..."
     after_failure:
-      # print some debug info
+      # print debug info
       - cat ~/.keptn/keptn-installer.log
       - kubectl get events --sort-by='.lastTimestamp' --all-namespaces
       - kubectl get pods --all-namespaces
@@ -610,10 +605,10 @@ jobs:
       - export DYNATRACE_SLI_SERVICE_VERSION=master
       - test/test_quality_gates_standalone.sh
     after_success:
-      # delete google kubernetes cluster only on success (in case of an error we want to be able to dig into the cluster)
+      # delete Google Kubernetes cluster only on success (keep cluster in case of an error to dig into the cluster)
       - echo "Tests were successful, cleaning up the cluster now..."
     after_failure:
-      # print some debug info
+      # print debug info
       - echo "Keptn Installation Log:"
       - cat ~/.keptn/keptn-installer.log
       - kubectl get events --sort-by='.lastTimestamp' --all-namespaces
@@ -649,10 +644,10 @@ jobs:
       - export DYNATRACE_SLI_SERVICE_VERSION=master
       - test/test_quality_gates_standalone.sh
     after_success:
-      # delete kubernetes cluster only on success (in case of an error we want to be able to dig into the cluster)
+      # delete Google Kubernetes cluster only on success (keep cluster in case of an error to dig into the cluster)
       - echo "Tests were successful, cleaning up the cluster now..."
     after_failure:
-      # print some debug info
+      # print debug info
       - cat ~/.keptn/keptn-installer.log
       - kubectl get events --sort-by='.lastTimestamp' --all-namespaces
       - kubectl get pods --all-namespaces
@@ -668,14 +663,13 @@ jobs:
       - MICROK8S_VERSION=1.18/stable # see https://snapcraft.io/microk8s channels
 
   - &minikubeStandaloneTest
-    stage: Test Minikube Standalone (--platform=kubernetes)
-    # for detailed Minikube versions see https://github.com/kubernetes/minikube/blob/master/CHANGELOG.md
+    stage: Test Minikube Standalone (--platform=kubernetes) # for detailed Minikube versions see https://github.com/kubernetes/minikube/blob/master/CHANGELOG.md
     env:
       - MINIKUBE_VERSION=v1.3.1 # from 2019-08-13; uses K8s 1.15
     if: (branch = master or branch =~ ^release.*$) AND (type = cron OR type = push) # run for any change on master/release-* on push as well as cron
     os: linux
     before_script:
-      # install conntrack (required for newer minikube versions)
+      # install conntrack (required for newer Minikube versions)
       - sudo apt-get install -y conntrack
       # download and install kubectl
       - curl -LO https://storage.googleapis.com/kubernetes-release/release/v1.17.0/bin/linux/amd64/kubectl && chmod +x ./kubectl && sudo mv ./kubectl /usr/local/bin/kubectl
@@ -684,17 +678,17 @@ jobs:
       - test/utils/minikube_create_cluster.sh
     script:
       - kubectl get nodes || travis_terminate 1 # sanity check that the K8s cluster is available
-      # finally install keptn quality gates
+      # install keptn quality gates
       - test/test_install_kubernetes_quality_gates.sh
       - keptn status
       - export PROJECT=musicshop
       - export DYNATRACE_SLI_SERVICE_VERSION=master
       - test/test_quality_gates_standalone.sh
     after_success:
-      # delete google kubernetes cluster only on success (in case of an error we want to be able to dig into the cluster)
+      # delete Google Kubernetes cluster only on success (keep cluster in case of an error to dig into the cluster)
       - echo "Tests were successful, cleaning up the cluster now..."
     after_failure:
-      # print some debug info
+      # print debug info
       - cat ~/.keptn/keptn-installer.log
       - kubectl get events --sort-by='.lastTimestamp' --all-namespaces
       - kubectl get pods --all-namespaces
