ci: Speed up docker builds by running them in parallel (#4778)
Signed-off-by: Moritz Wiesinger <moritz.wiesinger@dynatrace.com>

diff --git a/.github/workflows/CI.yml b/.github/workflows/CI.yml
--- a/.github/workflows/CI.yml
+++ b/.github/workflows/CI.yml
@@ -34,7 +34,6 @@ jobs:
       BUILD_HELM_SVC: ${{ steps.check_modified_files.outputs.BUILD_HELM_SVC }}
       BUILD_APPROVAL_SVC: ${{ steps.check_modified_files.outputs.BUILD_APPROVAL_SVC }}
       BUILD_DISTRIBUTOR: ${{ steps.check_modified_files.outputs.BUILD_DISTRIBUTOR }}
-      BUILD_EVENTBROKER: ${{ steps.check_modified_files.outputs.BUILD_EVENTBROKER }}
       BUILD_SHIPYARD_CONTROLLER: ${{ steps.check_modified_files.outputs.BUILD_SHIPYARD_CONTROLLER }}
       BUILD_SECRET_SVC: ${{ steps.check_modified_files.outputs.BUILD_SECRET_SVC }}
       BUILD_CONFIGURATION_SVC: ${{ steps.check_modified_files.outputs.BUILD_CONFIGURATION_SVC }}
@@ -107,7 +106,6 @@ jobs:
           BUILD_HELM_SVC=false
           BUILD_APPROVAL_SVC=false
           BUILD_DISTRIBUTOR=false
-          BUILD_EVENTBROKER=false
           BUILD_SHIPYARD_CONTROLLER=false
           BUILD_SECRET_SVC=false
           BUILD_CONFIGURATION_SVC=false
@@ -160,10 +158,6 @@ jobs:
               BUILD_DISTRIBUTOR=true
             fi
 
-            if [[ $changed_file == "${EVENTBROKER_FOLDER}"* ]]; then
-              BUILD_EVENTBROKER=true
-            fi
-
             if [[ $changed_file == "${SHIPYARD_CONTROLLER_FOLDER}"* ]]; then
               BUILD_SHIPYARD_CONTROLLER=true
             fi
@@ -203,7 +197,6 @@ jobs:
           echo "##[set-output name=BUILD_HELM_SVC;]$(echo ${BUILD_HELM_SVC})"
           echo "##[set-output name=BUILD_APPROVAL_SVC;]$(echo ${BUILD_APPROVAL_SVC})"
           echo "##[set-output name=BUILD_DISTRIBUTOR;]$(echo ${BUILD_DISTRIBUTOR})"
-          echo "##[set-output name=BUILD_EVENTBROKER;]$(echo ${BUILD_EVENTBROKER})"
           echo "##[set-output name=BUILD_SHIPYARD_CONTROLLER;]$(echo ${BUILD_SHIPYARD_CONTROLLER})"
           echo "##[set-output name=BUILD_SECRET_SVC;]$(echo ${BUILD_SECRET_SVC})"
           echo "##[set-output name=BUILD_CONFIGURATION_SVC;]$(echo ${BUILD_CONFIGURATION_SVC})"
@@ -625,10 +618,72 @@ jobs:
   ############################################################################
   # Build Docker Images                                                      #
   ############################################################################
-  docker_build:
+  prepare_github_pr_comment:
     needs: [prepare_ci_run, unit-tests-go-microservices, unit-tests-node]
+    name: Prepare GitHub Report Comment
+    runs-on: ubuntu-20.04
+    steps:
+      - name: Create PR comment
+        if: (github.event_name == 'pull_request') && (github.event.pull_request.head.repo.full_name == github.repository)
+        # only run if this is not a fork - see https://github.com/marocchino/sticky-pull-request-comment/issues/227
+        # note: GH does not allow to access secrets for PRs from a forked repositories due to security reasons
+        # that's fine, but it means we can't comment on the PR in this case
+        uses: marocchino/sticky-pull-request-comment@v2.1.0
+        continue-on-error: true
+        with:
+          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+          message: "Docker Build Report"
+          recreate: true
+
+  docker_build:
+    needs: [prepare_ci_run, unit-tests-go-microservices, unit-tests-node, prepare_github_pr_comment]
     name: Docker Build
     runs-on: ubuntu-20.04
+    strategy:
+      matrix:
+        config:
+          - ARTIFACT: "api"
+            BUILD_FOLDER: "api/"
+            SHOULD_BUILD: "${{ needs.prepare_ci_run.outputs.BUILD_API }}"
+          - ARTIFACT: "bridge2"
+            BUILD_FOLDER: "bridge/"
+            SHOULD_BUILD: "${{ needs.prepare_ci_run.outputs.BUILD_BRIDGE }}"
+          - ARTIFACT: "distributor"
+            BUILD_FOLDER: "distributor/"
+            SHOULD_BUILD: "${{ needs.prepare_ci_run.outputs.BUILD_DISTRIBUTOR }}"
+          - ARTIFACT: "jmeter-service"
+            BUILD_FOLDER: "jmeter-service/"
+            SHOULD_BUILD: "${{ needs.prepare_ci_run.outputs.BUILD_JMETER }}"
+          - ARTIFACT: "helm-service"
+            BUILD_FOLDER: "helm-service/"
+            SHOULD_BUILD: "${{ needs.prepare_ci_run.outputs.BUILD_HELM_SVC }}"
+          - ARTIFACT: "approval-service"
+            BUILD_FOLDER: "approval-service/"
+            SHOULD_BUILD: "${{ needs.prepare_ci_run.outputs.BUILD_APPROVAL_SVC }}"
+          - ARTIFACT: "openshift-route-service"
+            BUILD_FOLDER: "platform-support/openshift-route-service/"
+            SHOULD_BUILD: "${{ needs.prepare_ci_run.outputs.BUILD_OS_ROUTE_SVC }}"
+          - ARTIFACT: "shipyard-controller"
+            BUILD_FOLDER: "shipyard-controller/"
+            SHOULD_BUILD: "${{ needs.prepare_ci_run.outputs.BUILD_SHIPYARD_CONTROLLER }}"
+          - ARTIFACT: "secret-service"
+            BUILD_FOLDER: "secret-service/"
+            SHOULD_BUILD: "${{ needs.prepare_ci_run.outputs.BUILD_SECRET_SVC }}"
+          - ARTIFACT: "configuration-service"
+            BUILD_FOLDER: "configuration-service/"
+            SHOULD_BUILD: "${{ needs.prepare_ci_run.outputs.BUILD_CONFIGURATION_SVC }}"
+          - ARTIFACT: "remediation-service"
+            BUILD_FOLDER: "remediation-service/"
+            SHOULD_BUILD: "${{ needs.prepare_ci_run.outputs.BUILD_REMEDIATION_SVC }}"
+          - ARTIFACT: "lighthouse-service"
+            BUILD_FOLDER: "lighthouse-service/"
+            SHOULD_BUILD: "${{ needs.prepare_ci_run.outputs.BUILD_LIGHTHOUSE_SVC }}"
+          - ARTIFACT: "mongodb-datastore"
+            BUILD_FOLDER: "mongodb-datastore/"
+            SHOULD_BUILD: "${{ needs.prepare_ci_run.outputs.BUILD_MONGODB_DS }}"
+          - ARTIFACT: "statistics-service"
+            BUILD_FOLDER: "statistics-service/"
+            SHOULD_BUILD: "${{ needs.prepare_ci_run.outputs.BUILD_STATISTICS_SVC }}"
     env:
       BRANCH: ${{ needs.prepare_ci_run.outputs.BRANCH }}
       VERSION: ${{ needs.prepare_ci_run.outputs.VERSION }}
@@ -655,169 +710,62 @@ jobs:
           REGISTRY_PASSWORD: ${{ secrets.REGISTRY_PASSWORD }}
         run: echo "$REGISTRY_PASSWORD" | docker login --username $REGISTRY_USER --password-stdin
 
-      - id: docker_build_api
-        name: Docker Build api-service
-        if: (needs.prepare_ci_run.outputs.BUILD_EVERYTHING == 'true') || (needs.prepare_ci_run.outputs.BUILD_API == 'true')
-        uses: keptn/gh-action-build-docker-image@master
+      - id: docker_cache
+        name: Docker Cache
+        uses: satackey/action-docker-layer-caching@v0.0.11
+        continue-on-error: true
         with:
+          key: docker-build-cache-${{ github.workflow }}-${{ matrix.config.ARTIFACT }}-{hash}
+          restore-keys: |
+            docker-build-cache-${{ github.workflow }}-${{ matrix.config.ARTIFACT }}
+
+      - id: docker_build_image
+        name: "Docker Build keptn/${{ matrix.config.ARTIFACT }}"
+        if: (needs.prepare_ci_run.outputs.BUILD_EVERYTHING == 'true') || (matrix.config.SHOULD_BUILD == 'true')
+        env:
           VERSION: ${{ env.VERSION }}
           DATETIME: ${{ env.DATETIME }}
-          IMAGE_NAME: "${{ env.DOCKER_ORGANIZATION }}/${{ env.API_IMAGE }}"
-          DOCKER_FOLDER: ${{ env.API_FOLDER }}
-
-      - id: docker_build_bridge
-        name: Docker Build Bridge
-        if: (needs.prepare_ci_run.outputs.BUILD_EVERYTHING == 'true') || (needs.prepare_ci_run.outputs.BUILD_BRIDGE == 'true')
-        uses: keptn/gh-action-build-docker-image@master
-        with:
-          VERSION: ${{ env.VERSION }}
-          DATETIME: ${{ env.DATETIME }}
-          IMAGE_NAME: "${{ env.DOCKER_ORGANIZATION }}/${{ env.BRIDGE_IMAGE }}"
-          DOCKER_FOLDER: ${{ env.BRIDGE_FOLDER }}
-
-      - id: docker_build_distributor
-        name: Docker Build Distributor
-        if: (needs.prepare_ci_run.outputs.BUILD_EVERYTHING == 'true') || (needs.prepare_ci_run.outputs.BUILD_DISTRIBUTOR == 'true')
-        uses: keptn/gh-action-build-docker-image@master
-        with:
-          VERSION: ${{ env.VERSION }}
-          DATETIME: ${{ env.DATETIME }}
-          IMAGE_NAME: "${{ env.DOCKER_ORGANIZATION }}/${{ env.DISTRIBUTOR_IMAGE }}"
-          DOCKER_FOLDER: ${{ env.DISTRIBUTOR_FOLDER }}
-
-      - id: docker_build_jmeter_service
-        name: Docker Build jmeter-service
-        if: (needs.prepare_ci_run.outputs.BUILD_EVERYTHING == 'true') || (needs.prepare_ci_run.outputs.BUILD_JMETER == 'true')
-        uses: keptn/gh-action-build-docker-image@master
-        with:
-          VERSION: ${{ env.VERSION }}
-          DATETIME: ${{ env.DATETIME }}
-          IMAGE_NAME: "${{ env.DOCKER_ORGANIZATION }}/${{ env.JMETER_SVC_IMAGE }}"
-          DOCKER_FOLDER: ${{ env.JMETER_SVC_FOLDER }}
-
-      - id: docker_build_helm_service
-        name: Docker Build helm-service
-        if: (needs.prepare_ci_run.outputs.BUILD_EVERYTHING == 'true') || (needs.prepare_ci_run.outputs.BUILD_HELM_SVC == 'true')
-        uses: keptn/gh-action-build-docker-image@master
-        with:
-          VERSION: ${{ env.VERSION }}
-          DATETIME: ${{ env.DATETIME }}
-          IMAGE_NAME: "${{ env.DOCKER_ORGANIZATION }}/${{ env.HELM_SVC_IMAGE }}"
-          DOCKER_FOLDER: ${{ env.HELM_SVC_FOLDER }}
-
-      - id: docker_build_approval_service
-        name: Docker Build approval-service
-        if: (needs.prepare_ci_run.outputs.BUILD_EVERYTHING == 'true') || (needs.prepare_ci_run.outputs.BUILD_APPROVAL_SVC == 'true')
-        uses: keptn/gh-action-build-docker-image@master
-        with:
-          VERSION: ${{ env.VERSION }}
-          DATETIME: ${{ env.DATETIME }}
-          IMAGE_NAME: "${{ env.DOCKER_ORGANIZATION }}/${{ env.APPROVAL_SVC_IMAGE }}"
-          DOCKER_FOLDER: ${{ env.APPROVAL_SVC_FOLDER }}
-
-      - id: docker_build_os_route_service
-        name: Docker Build openshift-route-service
-        if: (needs.prepare_ci_run.outputs.BUILD_EVERYTHING == 'true') || (needs.prepare_ci_run.outputs.BUILD_OS_ROUTE_SVC == 'true')
-        uses: keptn/gh-action-build-docker-image@master
-        with:
-          VERSION: ${{ env.VERSION }}
-          DATETIME: ${{ env.DATETIME }}
-          IMAGE_NAME: "${{ env.DOCKER_ORGANIZATION }}/${{ env.OS_ROUTE_SVC_IMAGE }}"
-          DOCKER_FOLDER: ${{ env.OS_ROUTE_SVC_FOLDER }}
-
-      - id: docker_build_shipyard_controller
-        name: Docker Build shipyard-controller
-        if: (needs.prepare_ci_run.outputs.BUILD_EVERYTHING == 'true') || (needs.prepare_ci_run.outputs.BUILD_SHIPYARD_CONTROLLER == 'true')
-        uses: keptn/gh-action-build-docker-image@master
-        with:
-          VERSION: ${{ env.VERSION }}
-          DATETIME: ${{ env.DATETIME }}
-          IMAGE_NAME: "${{ env.DOCKER_ORGANIZATION }}/${{ env.SHIPYARD_CONTROLLER_IMAGE }}"
-          DOCKER_FOLDER: ${{ env.SHIPYARD_CONTROLLER_FOLDER }}
-
-      - id: docker_build_secret_service
-        name: Docker Build secret-service
-        if: (needs.prepare_ci_run.outputs.BUILD_EVERYTHING == 'true') || (needs.prepare_ci_run.outputs.BUILD_SECRET_SVC == 'true')
-        uses: keptn/gh-action-build-docker-image@master
-        with:
-          VERSION: ${{ env.VERSION }}
-          DATETIME: ${{ env.DATETIME }}
-          IMAGE_NAME: "${{ env.DOCKER_ORGANIZATION }}/${{ env.SECRET_SVC_IMAGE }}"
-          DOCKER_FOLDER: ${{ env.SECRET_SVC_FOLDER }}
-
-      - id: docker_build_configuration_service
-        name: Docker Build configuration-service
-        if: (needs.prepare_ci_run.outputs.BUILD_EVERYTHING == 'true') || (needs.prepare_ci_run.outputs.BUILD_CONFIGURATION_SVC == 'true')
-        uses: keptn/gh-action-build-docker-image@master
-        with:
-          VERSION: ${{ env.VERSION }}
-          DATETIME: ${{ env.DATETIME }}
-          IMAGE_NAME: "${{ env.DOCKER_ORGANIZATION }}/${{ env.CONFIGURATION_SVC_IMAGE }}"
-          DOCKER_FOLDER: ${{ env.CONFIGURATION_SVC_FOLDER }}
-
-      - id: docker_build_remediation_service
-        name: Docker Build remediation-service
-        if: (needs.prepare_ci_run.outputs.BUILD_EVERYTHING == 'true') || (needs.prepare_ci_run.outputs.BUILD_REMEDIATION_SVC == 'true')
-        uses: keptn/gh-action-build-docker-image@master
-        with:
-          VERSION: ${{ env.VERSION }}
-          DATETIME: ${{ env.DATETIME }}
-          IMAGE_NAME: "${{ env.DOCKER_ORGANIZATION }}/${{ env.REMEDIATION_SVC_IMAGE }}"
-          DOCKER_FOLDER: ${{ env.REMEDIATION_SVC_FOLDER }}
-
-      - id: docker_build_lighthouse_service
-        name: Docker Build lighthouse-service
-        if: (needs.prepare_ci_run.outputs.BUILD_EVERYTHING == 'true') || (needs.prepare_ci_run.outputs.BUILD_LIGHTHOUSE_SVC == 'true')
-        uses: keptn/gh-action-build-docker-image@master
-        with:
-          VERSION: ${{ env.VERSION }}
-          DATETIME: ${{ env.DATETIME }}
-          IMAGE_NAME: "${{ env.DOCKER_ORGANIZATION }}/${{ env.LIGHTHOUSE_SVC_IMAGE }}"
-          DOCKER_FOLDER: ${{ env.LIGHTHOUSE_SVC_FOLDER }}
-
-      - id: docker_build_mongodb_ds
-        name: Docker Build mongodb-datastore
-        if: (needs.prepare_ci_run.outputs.BUILD_EVERYTHING == 'true') || (needs.prepare_ci_run.outputs.BUILD_MONGODB_DS == 'true')
-        uses: keptn/gh-action-build-docker-image@master
-        with:
-          VERSION: ${{ env.VERSION }}
-          DATETIME: ${{ env.DATETIME }}
-          IMAGE_NAME: "${{ env.DOCKER_ORGANIZATION }}/${{ env.MONGODB_DS_IMAGE }}"
-          DOCKER_FOLDER: ${{ env.MONGODB_DS_FOLDER }}
-
-      - id: docker_build_statistics_service
-        name: Docker Build statistics-service
-        if: (needs.prepare_ci_run.outputs.BUILD_EVERYTHING == 'true') || (needs.prepare_ci_run.outputs.BUILD_STATISTICS_SVC == 'true')
-        uses: keptn/gh-action-build-docker-image@master
-        with:
-          VERSION: ${{ env.VERSION }}
-          DATETIME: ${{ env.DATETIME }}
-          IMAGE_NAME: "${{ env.DOCKER_ORGANIZATION }}/${{ env.STATISTICS_SVC_IMAGE }}"
-          DOCKER_FOLDER: ${{ env.STATISTICS_SVC_FOLDER }}
-
-      - id: create_docker_build_report
-        name: Create Docker Build Report
+          IMAGE: keptn/${{ matrix.config.ARTIFACT }}
+          DOCKER_FOLDER: ${{ matrix.config.BUILD_FOLDER }}
         run: |
-          echo "The following Docker Images have been built: " > docker_build_report_final.txt
-          cat docker_build_report.txt >> docker_build_report_final.txt || echo "* No images have been built or uploaded" >> docker_build_report_final.txt
-          echo "---"
-          cat docker_build_report_final.txt
+          DATETIME=$(date +'%Y%m%d')$(date +'%H%M')
+          docker build "${DOCKER_FOLDER}" -t "${IMAGE}:${VERSION}.${DATETIME}" -t "${IMAGE}:${VERSION}" --build-arg version="${VERSION}"
+          docker push "${IMAGE}:${VERSION}.${DATETIME}" && docker push "${IMAGE}:${VERSION}"
 
-      - id: report_docker_build_to_pr
-        name: Report Docker Build to PR
-        if: (github.event_name == 'pull_request') && (github.event.pull_request.head.repo.full_name == github.repository)
+          if [[ $? -ne 0 ]]; then
+            echo "::warning file=${DOCKER_FOLDER}/Dockerfile::Failed to push ${IMAGE}:${VERSION}.${DATETIME} to DockerHub, continuing anyway"
+            report="* Failed to push ${IMAGE}:${VERSION}.${DATETIME} and ${IMAGE}:${VERSION} (Source: ${DOCKER_FOLDER})"
+          else
+            report="* Pushed ${IMAGE}:${VERSION}.${DATETIME} and ${IMAGE}:${VERSION} (Source: ${DOCKER_FOLDER})"
+          fi
+
+          echo "::set-output name=build-report::$report"
+
+      - name: Report Docker Build to PR
+        if: always() && (github.event_name == 'pull_request') && (github.event.pull_request.head.repo.full_name == github.repository)
         # only run if this is not a fork - see https://github.com/marocchino/sticky-pull-request-comment/issues/227
         # note: GH does not allow to access secrets for PRs from a forked repositories due to security reasons
         # that's fine, but it means we can't comment on the PR in this case
         uses: marocchino/sticky-pull-request-comment@v2.1.0
+        continue-on-error: true
         with:
           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
-          path: docker_build_report_final.txt
-          recreate: true
+          message: ${{ steps.docker_build_image.outputs.build-report }}
+          append: true
 
-      - name: Upload Docker Build Report as an artifact
-        id: upload_docker_build_report
-        uses: actions/upload-artifact@v2
+      - name: Delete PR comment on failure
+        if: failure() && (github.event_name == 'pull_request') && (github.event.pull_request.head.repo.full_name == github.repository)
+        # only run if this is not a fork - see https://github.com/marocchino/sticky-pull-request-comment/issues/227
+        # note: GH does not allow to access secrets for PRs from a forked repositories due to security reasons
+        # that's fine, but it means we can't comment on the PR in this case
+        uses: marocchino/sticky-pull-request-comment@v2.1.0
+        continue-on-error: true
         with:
-          name: docker-build-report
-          path: docker_build_report.txt
+          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+          delete: true
+
+      - id: docker_logout
+        if: always()
+        name: Docker logout
+        run: |
+          docker logout
