ci: Ensure ZD pipeline fails if any test fails (#7964)
* try

Signed-off-by: RealAnna <anna.reale@dynatrace.com>

* added failure check for bth ui and go tests

Signed-off-by: RealAnna <anna.reale@dynatrace.com>

added failure check for bth ui and go tests

Signed-off-by: RealAnna <anna.reale@dynatrace.com>

added failure check for bth ui and go tests

Signed-off-by: RealAnna <anna.reale@dynatrace.com>

added failure check for bth ui and go tests

Signed-off-by: RealAnna <anna.reale@dynatrace.com>

added failure check for bth ui and go tests

Signed-off-by: RealAnna <anna.reale@dynatrace.com>

* fix: Ensure ZD pipeline fails if any test fails

Signed-off-by: RealAnna <anna.reale@dynatrace.com>

* fix: Ensure ZD pipeline fails if any test fails

Signed-off-by: RealAnna <anna.reale@dynatrace.com>

* fix: Ensure ZD pipeline fails if any test fails

Signed-off-by: RealAnna <anna.reale@dynatrace.com>

* fix: Ensure ZD pipeline fails if any test fails

Signed-off-by: RealAnna <anna.reale@dynatrace.com>

* fix: Ensure ZD pipeline fails if any test fails

Signed-off-by: RealAnna <anna.reale@dynatrace.com>

* fix: Ensure ZD pipeline fails if any test fails

Signed-off-by: RealAnna <anna.reale@dynatrace.com>

* fix: Ensure ZD pipeline fails if any test fails

Signed-off-by: RealAnna <anna.reale@dynatrace.com>

* fix: Ensure ZD pipeline fails if any test fails

Signed-off-by: RealAnna <anna.reale@dynatrace.com>

* fix: Ensure ZD pipeline fails if any test fails

Signed-off-by: RealAnna <anna.reale@dynatrace.com>

* fix: Ensure ZD pipeline fails if any test fails

Signed-off-by: RealAnna <anna.reale@dynatrace.com>

* fix: Ensure ZD pipeline fails if any test fails

Signed-off-by: RealAnna <anna.reale@dynatrace.com>

* according to review

Signed-off-by: RealAnna <anna.reale@dynatrace.com>

* fix

Signed-off-by: RealAnna <anna.reale@dynatrace.com>

diff --git a/.github/workflows/zero-downtime-tests.yml b/.github/workflows/zero-downtime-tests.yml
--- a/.github/workflows/zero-downtime-tests.yml
+++ b/.github/workflows/zero-downtime-tests.yml
@@ -358,26 +358,32 @@ jobs:
       #######################################################################
 
       - name: Zero Downtime Tests
-        id: test_zero_downtime
         timeout-minutes: 90
         working-directory: test/zero-downtime
+        id: test_zero_downtime
         env:
           GOMAXPROCS: 10
           KEPTN_ENDPOINT: ${{ steps.determine_keptn_endpoint.outputs.KEPTN_ENDPOINT }}
         run: |
           set -euo pipefail 
           
-           go test -json -v -run Test_ZeroDowntime -v -timeout 90m 2>&1 | tee /tmp/gotest.log &
-           cd ../../bridge &&
-           if [[ "${{ github.event.inputs.testUI }}" == 'true' ]]; then   
+          go test -json -v -run Test_ZeroDowntime -v -timeout 90m 2>&1 | tee /tmp/gotest.log & GOTEST=$!
+
+          cd ../../bridge &&
+          if [[ "${{ github.event.inputs.testUI }}" == 'true' ]]; then
             while [[ $(jobs -pr) ]]; do
               echo "New Run: "  >> /tmp/uitest.log 
               npm run test:ui >> /tmp/uitest.log 2>&1 
             done
           else
             echo "UI tests will not run"
-          fi 
-
+          fi
+        
+          wait $GOTEST
+          if [[ $? -ne 0 ]]; then
+            echo "::error::Zero Downtime go test failed - exiting"
+            exit 1
+          fi
 
       - name: Format go test log output
         if: always()
